### ISSUE TITLE
Hide api key in .env file

### ISSUE THREAD

**Issue by BelkinMax** [Artikoar/spltracker#2]
Never expose your private data such as login, password or keys. This kind of data should be stored in `.env` file.

https://www.youtube.com/watch?v=47pHZYtciEs&t=1207s

**Comment by Artikoar** [comment]
If you're speaking about Mapbox GL access token, it can't be hidden server-side as I know.
[ToU of Mapbox](https://www.mapbox.com/tos/#[YmaMYmns]):
> You may not redistribute Map Assets, including from a cache, by proxying, or by using a screenshot or other static image instead of accessing Map Assets through the Mapping APIs.

Fortunaly, Mapbox allows to restrict token usage by domain. I will work on that.
